spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assignment
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        jdbc:
          lob:
            non_contextual_creation: true